### PR TITLE
Fix "Error: Cannot find module 'vscode'" in dev package

### PR DESCRIPTION
**Pull request by EricJizbaMSFT**
I have to use `_vscode` when I call `new EventEmitter<types.PromptResult>` otherwise tests will fail

The problem was introduced in https://github.com/microsoft/vscode-azuretools/pull/687

### CODE REVIEW

File: dev/src/TestUserInput.ts [hunk 1]
```diff
@@ -4,7 +4,7 @@
  *--------------------------------------------------------------------------------------------*/
 
 import * as assert from 'assert';
-import { Event, EventEmitter, InputBoxOptions, MessageItem, MessageOptions, OpenDialogOptions, QuickPickItem, QuickPickOptions, Uri } from 'vscode';
+import * as vscodeTypes from 'vscode'; // `TestUserInput._vscode` should be use for anything that's not purely a type (e.g. instantiating a class)
```
Comment (wwlorey) [inline dev/src/TestUserInput.ts:7]: nit: just a small grammar thing:
```suggestion
import * as vscodeTypes from 'vscode'; // `TestUserInput._vscode` should be used for anything that's not purely a type (e.g. instantiating a class)
```
